table game_platforms
	lineageTag: 3d1bb845-24dc-4012-9f70-44505b8c9a97

	column game_id
		dataType: int64
		formatString: 0
		lineageTag: 7ca9d46a-ae51-4fab-99a2-2476680f5d3e
		summarizeBy: none
		sourceColumn: game_id

		annotation SummarizationSetBy = Automatic

	column platforms
		dataType: string
		lineageTag: 426644ee-e756-4033-8bbf-6105078dae9b
		summarizeBy: none
		sourceColumn: platforms

		annotation SummarizationSetBy = Automatic

	partition game_platforms = m
		mode: import
		source =
				let
				    Source = dim_game,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"game_id", "platforms"}),
				    #"Expanded platforms" = Table.ExpandListColumn(#"Removed Other Columns", "platforms"),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded platforms"),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Duplicates", {"platforms"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each ([platforms] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

